Update runtime to 46
flathub/org.gnome.Totem pull request #104
Opened 2023-10-03 15:21 UTC by A6GibKm

Closes https://github.com/flathub/org.gnome.Totem/issues/103

2023-10-03 18:22 UTC, A6GibKm commented on org.gnome.Totem.json
> -        "codecs/ffmpeg.json",
I think it was

2023-10-03 18:58 UTC, bbhtt commented on org.gnome.Totem.json
> -        "codecs/ffmpeg.json",
https://github.com/flathub/io.github.celluloid_player.Celluloid/blob/master/ffmpeg-binutils.patch this was on top of 6.0 but I think it'll apply on 5.0 as well

2023-10-03 19:37 UTC, A6GibKm commented on org.gnome.Totem.json
> -        "codecs/ffmpeg.json",
Done, thanks. I wonder if this should be updated to 6.0 tho.

2023-10-16 08:31 UTC, hadess commented
I was certain that I commented here when the PR was posted, but it seems I didn't. Any packaging updates like module or runtime upgrades need to go through the repo at https://github.com/flathub/org.gnome.Totem.Devel

I've cherry-picked the changes in this PR to https://github.com/flathub/org.gnome.Totem.Devel/pull/24

2023-10-16 09:38 UTC, A6GibKm commented
Is anyone testing the Devel package?

2023-10-16 11:41 UTC, hadess commented
> Is anyone testing the Devel package?

I do. It's also the package we recommend testing if the stable release isn't working as we've removed the nightlies from the GNOME servers.

2023-10-27 21:43 UTC, A6GibKm commented
Some syslogs from running the app

```
oct 27 23:40:59 thinkpad systemd[2043]: Started dbus-:1.2-org.gnome.Totem.dleyna\x2dserver@11.service.
oct 27 23:40:59 thinkpad systemd[2043]: Started dbus-:1.2-org.gnome.Totem.Tracker3.Miner.Files@6.service.
oct 27 23:40:59 thinkpad systemd[2043]: Started app-flatpak-org.gnome.Totem-586019.scope.
oct 27 23:40:59 thinkpad systemd[2043]: Started app-flatpak-org.gnome.Totem-586027.scope.
oct 27 23:40:59 thinkpad systemd[2043]: dbus-:1.2-org.gnome.Totem.dleyna\x2dserver@11.service: Main process exited, code=exited, status=1/FAILURE
oct 27 23:40:59 thinkpad systemd[2043]: dbus-:1.2-org.gnome.Totem.dleyna\x2dserver@11.service: Failed with result 'exit-code'.
oct 27 23:40:59 thinkpad systemd[2043]: Started dbus-:1.2-org.gnome.Totem.dleyna\x2dserver@12.service.
```

```
oct 27 23:39:55 thinkpad tracker-extract[585844]: Could not create extraction controller: Cannot invoke method; proxy is for the well-known name org.freedesktop.Tracker3.Miner.Files without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

2023-10-27 21:44 UTC, A6GibKm commented
Another thing I noticed is that the manifest upstream does not build tracker inside the sandbox.

2023-10-28 07:38 UTC, A6GibKm commented
@hadess with the latest changes tracker works. No idea how it worked in the past.

2023-10-28 07:49 UTC, A6GibKm commented
Note that we are missing this lines https://gitlab.gnome.org/GNOME/totem/-/blob/master/flatpak/org.gnome.Totem.Devel.json?ref_type=heads#L22, but I tried it and it didnt seem to change anything,

2023-11-16 18:50 UTC, A6GibKm commented
Bot, build

2023-11-16 18:50 UTC, A6GibKm commented
Bump. @hadess is anything missing?

2023-11-16 19:05 UTC, hadess commented
> Bump. @hadess is anything missing?

A working `org.gnome.Totem.Devel` build as mentioned in https://github.com/flathub/org.gnome.Totem/pull/104#issuecomment-1763986279

I haven't had time to figure out why it is/was broken.

2023-11-16 19:40 UTC, A6GibKm commented
Did you see the latest two commits added here? That fixes it on my end.

2023-11-16 20:57 UTC, hadess commented
> Did you see the latest two commits ([2d8c908](https://github.com/flathub/org.gnome.Totem/commit/2d8c9084cdfa0537c25db37e8042c5da69ec71df), [7566bde](https://github.com/flathub/org.gnome.Totem/commit/7566bdeda1510abb7d580a8a2b2c925b2762c86a)) added here? That fixes it on my end.

I didn't. I'll try to pick those up on my end and test, but as you might know I'm really strapped for time.

2023-11-20 09:06 UTC, hadess commented
> Did you see the latest two commits (https://github.com/flathub/org.gnome.Totem/commit/2d8c9084cdfa0537c25db37e8042c5da69ec71df, https://github.com/flathub/org.gnome.Totem/commit/7566bdeda1510abb7d580a8a2b2c925b2762c86a) added here? That fixes it on my end.

Unfortunately, those aren't fixes we can merge. They force the use of the host Tracker. Totem instead uses its own tracker instance that runs inside the container and doesn't leak data outside.

2023-11-21 12:50 UTC, ssssam commented
Hi @hadess - can you provide context here about the data leaks you expect to happen ? I've searched Tracker and Tracker Miners issue tracker for "leak" and turned up nothing relevant.

For context @A6GibKm asked me if I can help move this forward since I volunteer time towards helping maintain Tracker. I am not sure how to support though.

2024-01-14 18:10 UTC, A6GibKm commented
Is it preferable to block this issue on a problem for which there is no public evidence yet, rather using a runtime which is still supported? GNOME 43 was marked as EOL on September of last year.

I think it would be better to open an issue, all the other Tracker consumers are using the version in their system and it might be a good idea to fix this so everyone benefits from it.

2024-01-29 15:26 UTC, hadess commented
> Is it preferable to block this PR on a problem for which there is no public evidence yet,

This is a repeat issue that the upstream tracker maintainers just forget about each time I mention it. I have very very very limited time to work on totem, and this sort of issue and the endless need to have to justify the maintenance of my own software just drains my energy. So you'll have to wait a bit more I'm afraid.

2024-01-29 16:51 UTC, ssssam commented
If you wrote it down somewhere we might not forget.

2024-03-21 17:00 UTC, marcthe12 commented
As Gnome 46 has been released, has this been solved with gnome 46 runtime? Maybe we should try gnome 46 update?

2024-03-23 09:22 UTC, A6GibKm commented
Continuing this long standing tradition of sending a PR to update totem every cycle here is the latest iteration.

Since Flathub has strict checks for app metainfo nowadays older stable versions of the app won't build anymore and I used the current HEAD of upstream which contains the required patches. I could also backport them if thats more desirable.

> As Gnome 46 has been released, has this been solved with gnome 46 runtime? Maybe we should try gnome 46 update?

I don't see any issue upstream to follow, hence there is nothing to solve.

2024-03-23 22:29 UTC, A6GibKm commented
Small update, I was able to add back Tracker. 

The problem now is that the videos don't have thumbnails. But this is also a problem in the current stable version. Using the Tracker from host fixes this.

2024-10-22 13:32 UTC, AsciiWolf commented
I agree with Julian. Totem is (still) a core GNOME app and as such would deserve a little better care.

Also, its last release was more than two years ago (see [this ticket](https://gitlab.gnome.org/GNOME/totem/-/issues/624)).

This is **not great** and I hope that at least a new upstream version will get released until Totem gets probably replaced by something more suitable as a core app.

2024-10-22 14:30 UTC, hadess requested changes
I'd like to see an attempt at figuring out what the problem is with the thumbnailing, as it seems to be working fine for me.

I will also note that the usual process for updating this repo is to update what needs to be updating in https://github.com/flathub/org.gnome.Totem.Devel/ and then cherry-picking those changes into the stable branch.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> -            "config-opts": ["-Denable-easy-codec-installation=no"],
The build option isn't obsolete in the version of the software that's still in this file. The config option should be removed when the software is updated to the version that removes it. It's also still supported in the latest stable branch, so this commit should be dropped.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> +    "runtime-version": "45",
The runtime version change should be a separate commit.

2024-10-22 14:30 UTC, hadess commented on dleyna/dleyna.json
> -            "commit": "db67c3071af7d708a66ac6f13c31b052078955b2"
Please split the "DLNA" module updates from the gnome-desktop one.

2024-10-22 14:30 UTC, hadess commented on dleyna/gssdp.json
> +            "tag": "gssdp-1.6.2"
Please squash this into the "DLNA" modules update.

2024-10-22 14:30 UTC, hadess commented on dleyna/gupnp-av.json
> +            "commit": "4da2f88f891883f52a40ff92432119a6083167cb"
Please squash this into the "DLNA" module update commit, while keeping the commit message.

2024-10-22 14:30 UTC, hadess commented on codecs/ffmpeg-binutils.patch
> +From: Rémi Denis-Courmont <remi@remlab.net>
That's fine. Can you please file an issue to update to a newer ffmpeg major version against:
https://github.com/flathub/org.gnome.Totem.Devel/issues

You can reference this commit:
https://lwn.net/Articles/992496/

2024-10-22 14:30 UTC, hadess commented on codecs/ffmpeg.json
> +            "tag": "n5.0.3",
Commit message says 5.0.2.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> +                    "tag": "3.7.0"
This should be squashed into the earlier tracker update commit.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> +                "-Dlandlock=disabled",
This can be squashed into the tracker update commit as well, please keep the reference in the commit though.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> +                    "tag": "3.7.0"
This can probably go into the earlier tracker update commit.

2024-10-22 14:30 UTC, hadess commented on org.gnome.Totem.json
> +                    "tag": "0.5.0"
Maybe the gnome-desktop update should be in this commit.

2024-10-22 15:21 UTC, hadess commented
> Anyway, you can still try to allocate at least a little part of your free time to community work on basic things (like tagging a new version at least once a year or two - especially if most of the changes are already tested by the Flathub build). Or at least try to find a new maintainer - this also applies to this Flatpak.
> 
> I would love to help, however my time is probably even worse than yours. And I already maintain 30+ Flatpaks, contribute to countless Free Software projects and translate the whole GNOME desktop into Czech (because every other Czech translator gave up) - all in my free time.

I hope it's still fun for you because it really isn't for me. Especially when I read stuff like this that makes demands on what I should do in my free time. I haven't seen anyone contribute in any meaningful way to totem in years, so I'm not sure how I could find a new maintainer in this circumstance.

Anyway, this patchset is reviewed.

2024-10-22 19:26 UTC, AsciiWolf commented
> I hope it's still fun for you because it really isn't for me. Especially when I read stuff like this that makes demands on what I should do in my free time. I haven't seen anyone contribute in any meaningful way to totem in years, so I'm not sure how I could find a new maintainer in this circumstance.

Well, sometimes it's still fun, but sometimes it's far from it. But I feel that if I maintain some Free Software project or related stuff, I have certain responsibilities towards the community and the Linux desktop as a whole. But yeah, I am also attempting to minimize the amount of things I'm working on and focus more on the things that are important and/or beneficial to me.

I certainly did not want my previous comment to sound like I was demanding something from you. I was just unhappy with the state of Totem as a whole and did suggest you that if you do not have more time (or even paid work time) to work on Totem, occasionally allocating a _small enough amount_ of a non-paid time to Totem and other community work could be a realistic idea and it would still greatly help the project.

Anyway, thanks for making the new (long-awaited :-)) Totem release and for reviewing this PR!

2024-10-22 20:58 UTC, A6GibKm commented
@hadess I would like to personally apologize if my previous comments in this PR where abrasive in any way.

Regarding the PR itself, I have my plate full at the moment. If someone wants to work on it please do so, otherwise I will eventually pick it up, probably.

2025-03-20 23:58 UTC, AsciiWolf commented on org.gnome.Totem.json
> +    "runtime-version": "46",
```suggestion
    "runtime-version": "48",
```

2025-03-21 10:34 UTC, hadess commented
Obsoleted by https://github.com/flathub/org.gnome.Totem/pull/110

2025-03-21 10:34 UTC, closed without merging